### ISSUE TITLE
Can't upload PNGs

### ISSUE THREAD

**Issue by evefavretto** [33mhz/robin#14]
When trying to upload a screenshot, PNGs are greyed out on the Android picker. Tested on both a Motorola Moto Z Play with Android 7.1.1 and a Samsung Galaxy J1 mini with Android 5.1

**Comment by 33mhz** [comment]
Try again with the latest. Should work.

**Comment by evefavretto** [comment]
Nope, still doesn't let me pick a PNG.
This may be useful: https://developer.android.com/guide/topics/providers/document-provider.html

On both 5.1 and 7.1 when picking files it opens a Android SAF window.

**Comment by 33mhz** [comment]
It was limited to JPEG. Changed to allow any image, then check if it was JPEG, GIF, PNG, and if not, deny.
