### ISSUE TITLE
"Interactions" crashes the app

### ISSUE THREAD

**Issue by schmidt-fu** [33mhz/robin#23]
When I swipe to the "Mentions" tab and tap the "Interactions" button, the app crashes every time since the update (on a Samsung Galaxy S4 mini).

**Comment by schmidt-fu** [comment]
It also crashes on Channels and when deleting a post now. I sent in crash reports, once saw an OutOfMemoryError (despite the app just having been restarted).

**Comment by 33mhz** [comment]
Have you reinstalled since Friday?

**Comment by schmidt-fu** [comment]
I have today, it's running build 196.

**Comment by 33mhz** [comment]
The people who've had those issues with that build did not with 207.

**Comment by schmidt-fu** [comment]
I just updated to 207, still the same crashes.

Update: Delete post crashes with a Resource not loaded because of wrong type (a part of the delete post dialog). Crash report sent.

**Comment by 33mhz** [comment]
Confirmed the crash on post delete attempt (fails).

**Comment by 33mhz** [comment]
To be clear: you updated to build 207, with a fresh install, and it is crashing when you open channels or the Interactions tab?

**Comment by schmidt-fu** [comment]
There seem to be multiple causes to the crashes, as seen in stacktraces:
- OutOfMemoryError: Interactions tab, sometimes happens in FutureTask
- ClassCast exception (PostHolder and PostCollapsedHolder involved): Scrolling away from and back to first post of collapsed thread
- InflateException caused by Resource$NotFoundException "Resource not a drawable" in binary XML line 9, somewhere near TextView: Open Delete Post Dialog from my Profile

All of these could be reproduced on my smartphone with a freshly updated build #244, crash reports were sent. I haven't deleted the app completely yet.

Maybe it makes sense to split the issue, so discussion can be more focused on the respective causes.

**Comment by schmidt-fu** [comment]
To your last question: It crashes with an OutOfMemoryError in an AsynTask when I try to open Interactions, or Channels. This happens in build 244, and it already did in 207 (but maybe the OOM happened somewhere else, I can't tell for sure).

**Comment by 33mhz** [comment]
207 or 196 had bad calls, that I believe the app cached, and it's not going to fix without a reinstall or some magical cache fix. Interactions and channels shouldn't have issues, and those who had your issue reinstalled and it's fixed...

**Comment by schmidt-fu** [comment]
I have now reinstalled the app, and Channels and Interactions don't crash anymore.
I can still reproduce the Collapsed thread crash with more combinations, all along those lines:
- when I collapse it while it is not displayed (e.g. in thread view)
- it doesn't get updated in the main view (Personal stream/timeline) without Unified option set
- I scroll until the collapsed post isn't displayed
- Sometimes: I scroll down (or to the top) so far that content is reloaded from pnut
- I scroll back until the collapsed post should be in view
- It crashes with a "ClassCastException: PostHolder can't be casted to PostCollapsedHolder" (simplified)

I also can still reproduce the crash on Delete Post.

**Comment by 33mhz** [comment]
Collapse thread bug is #31.

I'll track the crash on delete in #33, as that is a separate issue as well.
