### ISSUE TITLE
Can't open follower/-ing profiles

### ISSUE THREAD

**Issue by schmidt-fu** [33mhz/robin#32]
When I open a user profile (e.g. my own) and swipe to the "Followers" tab, then tap a user, nothing happens. I would expect the follower's profile be openes.

**Comment by 33mhz** [comment]
This works for me. I may have accidentally made this so when I fixed threads. Seems unlikely!

**Comment by schmidt-fu** [comment]
Confirmed, I tried tapping the avatar instead of the username and it works.

Tapping the username just animates the row background color, with no real interaction possible. Confusing, but no restriction of functionality.

**Comment by 33mhz** [comment]
Tapping a grid in the app always animates the row background color; it's a characteristic of the forms, fwiw. The usernames in following/ers just doesn't do anything, which is consistent with having to tap avatars other places to go to profiles. Glad it works!
