### ISSUE TITLE
Cancel post button on different side than cancel message button

### ISSUE THREAD

**Issue by schmidt-fu** [33mhz/robin#36]
When you write a post, and hit the devices "Back" button, choosing the left button on the subsequent "Are you sure" dialog leaves the activity with no further side effect (right button saves to Drafts).

When you write a message, and hit "Back", the left button on the dialog with same title won't get you out (and the right side button deletes instead of saves your content).

This mismatch can be confusing and

**Comment by schmidt-fu** [comment]
...prevents a consistent behaviour for "I don't want to continue writing this" to be learned,

**Comment by 33mhz** [comment]
Agreed. I'll change it to be like this, on [X] of a post and message:

post:

```
Are you sure?
Discard all changes?
Save draft | Cancel | Yes
```

message:
```
Are you sure?
Discard all changes?
Cancel | Yes
```
